// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CenterWindow() {
  return window['go']['main']['App']['CenterWindow']();
}

export function ClearMediaTaskCache(arg1) {
  return window['go']['main']['App']['ClearMediaTaskCache'](arg1);
}

export function ClearSavedTenantToken() {
  return window['go']['main']['App']['ClearSavedTenantToken']();
}

export function ClearSystemLogs() {
  return window['go']['main']['App']['ClearSystemLogs']();
}

export function CollectWebPage(arg1) {
  return window['go']['main']['App']['CollectWebPage'](arg1);
}

export function CreateSite(arg1) {
  return window['go']['main']['App']['CreateSite'](arg1);
}

export function CreateTenant(arg1) {
  return window['go']['main']['App']['CreateTenant'](arg1);
}

export function DeleteLocalDraft(arg1) {
  return window['go']['main']['App']['DeleteLocalDraft'](arg1);
}

export function DeleteMediaTask(arg1) {
  return window['go']['main']['App']['DeleteMediaTask'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['main']['App']['DeleteSite'](arg1);
}

export function DeleteSubmitRecord(arg1) {
  return window['go']['main']['App']['DeleteSubmitRecord'](arg1);
}

export function DeleteSystemLog(arg1) {
  return window['go']['main']['App']['DeleteSystemLog'](arg1);
}

export function DeleteTenant(arg1) {
  return window['go']['main']['App']['DeleteTenant'](arg1);
}

export function DiscoverSiteTenants(arg1) {
  return window['go']['main']['App']['DiscoverSiteTenants'](arg1);
}

export function DownloadRemoteMedia(arg1) {
  return window['go']['main']['App']['DownloadRemoteMedia'](arg1);
}

export function GetDesktopBootstrap() {
  return window['go']['main']['App']['GetDesktopBootstrap']();
}

export function GetLocalDraft(arg1) {
  return window['go']['main']['App']['GetLocalDraft'](arg1);
}

export function ListLocalDrafts(arg1) {
  return window['go']['main']['App']['ListLocalDrafts'](arg1);
}

export function ListMediaTasks(arg1) {
  return window['go']['main']['App']['ListMediaTasks'](arg1);
}

export function ListSubmitRecords(arg1) {
  return window['go']['main']['App']['ListSubmitRecords'](arg1);
}

export function ListSystemLogs(arg1) {
  return window['go']['main']['App']['ListSystemLogs'](arg1);
}

export function LoginTenant(arg1) {
  return window['go']['main']['App']['LoginTenant'](arg1);
}

export function LogoutTenant(arg1) {
  return window['go']['main']['App']['LogoutTenant'](arg1);
}

export function LogoutTenantById(arg1) {
  return window['go']['main']['App']['LogoutTenantById'](arg1);
}

export function ProxyDesktopApiRequest(arg1) {
  return window['go']['main']['App']['ProxyDesktopApiRequest'](arg1);
}

export function RefreshTenantToken(arg1) {
  return window['go']['main']['App']['RefreshTenantToken'](arg1);
}

export function RenderWebPagePreview(arg1) {
  return window['go']['main']['App']['RenderWebPagePreview'](arg1);
}

export function RetryMediaTask(arg1) {
  return window['go']['main']['App']['RetryMediaTask'](arg1);
}

export function SaveLocalDraft(arg1) {
  return window['go']['main']['App']['SaveLocalDraft'](arg1);
}

export function SaveTenantAuth(arg1) {
  return window['go']['main']['App']['SaveTenantAuth'](arg1);
}

export function ScanSiteLinks(arg1) {
  return window['go']['main']['App']['ScanSiteLinks'](arg1);
}

export function SyncSiteTenants(arg1) {
  return window['go']['main']['App']['SyncSiteTenants'](arg1);
}

export function UpdateSite(arg1) {
  return window['go']['main']['App']['UpdateSite'](arg1);
}

export function UpdateTenant(arg1) {
  return window['go']['main']['App']['UpdateTenant'](arg1);
}

export function UploadDesktopMedia(arg1) {
  return window['go']['main']['App']['UploadDesktopMedia'](arg1);
}
