// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CenterWindow():Promise<void>;

export function ClearMediaTaskCache(arg1:model.MediaTaskCacheCleanupInput):Promise<void>;

export function ClearSavedTenantToken():Promise<void>;

export function ClearSystemLogs():Promise<void>;

export function CollectWebPage(arg1:model.CollectWebPageInput):Promise<model.CollectedWebPageResult>;

export function CreateSite(arg1:model.CreateSiteInput):Promise<model.SiteItem>;

export function CreateTenant(arg1:model.CreateTenantInput):Promise<model.TenantItem>;

export function DeleteLocalDraft(arg1:model.LocalDraftQueryInput):Promise<void>;

export function DeleteMediaTask(arg1:number):Promise<void>;

export function DeleteSite(arg1:model.DeleteSiteInput):Promise<void>;

export function DeleteSubmitRecord(arg1:number):Promise<void>;

export function DeleteSystemLog(arg1:number):Promise<void>;

export function DeleteTenant(arg1:model.DeleteTenantInput):Promise<void>;

export function DiscoverSiteTenants(arg1:model.DiscoverSiteTenantsInput):Promise<model.TenantDiscoveryPayload>;

export function DownloadRemoteMedia(arg1:model.DownloadRemoteMediaInput):Promise<model.DownloadRemoteMediaResult>;

export function GetDesktopBootstrap():Promise<model.DesktopBootstrap>;

export function GetLocalDraft(arg1:model.LocalDraftQueryInput):Promise<model.LocalDraftItem>;

export function ListLocalDrafts(arg1:model.LocalDraftListInput):Promise<Array<model.LocalDraftItem>>;

export function ListMediaTasks(arg1:model.MediaTaskListInput):Promise<Array<model.MediaTaskItem>>;

export function ListSubmitRecords(arg1:model.SubmitRecordListInput):Promise<Array<model.SubmitRecordItem>>;

export function ListSystemLogs(arg1:model.AppLogListInput):Promise<Array<model.AppLogItem>>;

export function LoginTenant(arg1:model.LoginTenantInput):Promise<model.AuthBootstrap>;

export function LogoutTenant(arg1:model.LogoutTenantInput):Promise<void>;

export function LogoutTenantById(arg1:number):Promise<void>;

export function ProxyDesktopApiRequest(arg1:model.RemoteDesktopAPIRequestInput):Promise<model.RemoteDesktopAPIResponse>;

export function RefreshTenantToken(arg1:model.RefreshTenantTokenInput):Promise<model.AuthBootstrap>;

export function RenderWebPagePreview(arg1:model.CollectWebPageInput):Promise<model.BrowserRenderedPreviewResult>;

export function RetryMediaTask(arg1:model.MediaTaskRetryInput):Promise<model.RemoteDesktopAPIResponse>;

export function SaveLocalDraft(arg1:model.SaveLocalDraftInput):Promise<model.LocalDraftItem>;

export function SaveTenantAuth(arg1:model.SaveTenantAuthInput):Promise<model.AuthBootstrap>;

export function ScanSiteLinks(arg1:model.ScanSiteLinksInput):Promise<model.ScanSiteLinksResult>;

export function SyncSiteTenants(arg1:model.SyncSiteTenantsInput):Promise<Array<model.TenantItem>>;

export function UpdateSite(arg1:model.UpdateSiteInput):Promise<model.SiteItem>;

export function UpdateTenant(arg1:model.UpdateTenantInput):Promise<model.TenantItem>;

export function UploadDesktopMedia(arg1:model.UploadDesktopMediaInput):Promise<model.RemoteDesktopAPIResponse>;
